// export const debitData = [
//       {
//         id: 5,
//         dataType: "Credit",
//         completed: "160",
//         maxCompleted: 290,
//         startDate: "12/02/2024",
//         endDate: "12/03/2024",
//         clientName: "Mark",
//       },
//       {
//         id: 1,
//         dataType: "Credit",
//         completed: "180",
//         maxCompleted: 200,
//         startDate: "12/05/2024",
//         endDate: "12/06/2024",
//         clientName: "Emma",
//       },
//       {
//         id: 2,
//         dataType: "Debit",
//         completed: "150",
//         maxCompleted: 320,
//         startDate: "12/10/2024",
//         endDate: "12/11/2024",
//         clientName: "John",
//       },
//       {
//         id: 3,
//         dataType: "Credit",
//         completed: "190",
//         maxCompleted: 200,
//         startDate: "12/15/2024",
//         endDate: "12/16/2024",
//         clientName: "Sarah",
//       },
//       {
//         id: 4,
//         dataType: "Debit",
//         completed: "175",
//         maxCompleted: 250,
//         startDate: "12/20/2024",
//         endDate: "12/21/2024",
//         clientName: "Michael",
//       },
//     ];